### PR TITLE
Add variables required for DynamoDB

### PR DESCRIPTION
**Pull request by jonnyshaw89**
- Added the environment variables required for DynamoDB
- Upgraded terraform to run dynamo and modify terraform parameters

### CODE REVIEW

**Review by nealedj — COMMENTED** [review]
How do the read/write capacity values get set?

**Comment by jonnyshaw89** [comment]
They autoscale

**Comment by nealedj** [comment]
But there's still a min/max isn't there? Doesn't removing these values prevent us from varying those capacity values across concourse-deployed environments? I.e. if we wanted staging to run with lower capacities.

**Comment by jonnyshaw89** [comment]
Staging runs at lower because it uses the developer bootstrap in the root of eq-terraform.

**Review by nealedj — APPROVED** [review]

**Review by kierenbeckett — APPROVED** [review]

**Pull request merged**
