### PR TITLE
Author - Deploy redis to preprod

### PR DESCRIPTION
**Pull request by tgandrews**
This adds a resource to reference the author terraform redis repository release and also adds it to the preprod environment only.

I copied the `application_cidrs` from the preprod task `Deploy Author Database`

### CODE REVIEW

**Comment by tgandrews** [comment]
[Validator - number notifications (8)](https://trello.com/c/8ynDssd8/1066-validator-number-notifications-8)

**Review by samiwel — APPROVED** [review]
LGTM

**Review by pricea1 — APPROVED** [review]
LGTM

**Comment by tgandrews** [comment]
This is blocked until author release is in production

**Pull request merged**
