### PR TITLE
Enable Google Tag Manager in Author staging environment

### PR DESCRIPTION
**Pull request by rmccar**
This is to add the variables needed to implement Google Tag Manager.

Depends on https://github.com/ONSdigital/eq-author-terraform/pull/8

### CODE REVIEW

**Review by samiwel — CHANGES_REQUESTED** [review]
The indentation changes have made it difficult to see what has changed in this diff. Can we undo all changes and ensure that the only changes are the two newly introduced variables?

**Review by samiwel — APPROVED** [review]

**Comment by jonnyshaw89** [comment]
What happened to Squashing commits and 2 reviewers?

**Comment by samiwel** [comment]
I think the merge without squashing was a genuine mistake. 2 reviews wasn't being enforced on this repo. I've just changed this so that PRs will be blocked in future without 2 approving reviews.

**Comment by rmccar** [comment]
Yeah as soon as I clicked merge I realised I'd forgotten to squash Im afraid. With the 2 reviewers I thought the rules must be slightly different on this repo because it allowed me to merge with one review. Also I looked in the closed PR list and there were quite a few merged in there with one review.

**Comment by jonnyshaw89** [comment]
@rmccar `author_google_tag_manager_id` and `staging_author_google_tag_manager_environment_id` are not in `secrets.yml.example` this needs to be added

**Pull request merged**
